# Generated by Django 5.2.7 on 2025-10-24 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix24UserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.IntegerField(verbose_name='Bitrix24 User ID')),
                ('bitrix_user_name', models.CharField(blank=True, max_length=255, verbose_name='Bitrix24 User Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitrix24 User Mapping',
                'verbose_name_plural': 'Bitrix24 User Mappings',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('missed', 'Missed')], max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recording', models.FileField(blank=True, max_length=500, null=True, upload_to='call_recordings/%Y/%m/%d/', verbose_name='Call Recording File')),
                ('recording_uploaded_to_bitrix', models.BooleanField(default=False, verbose_name='Recording uploaded to Bitrix24')),
                ('recording_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Recording upload timestamp')),
                ('bitrix_call_id', models.CharField(blank=True, max_length=200, null=True)),
                ('bitrix_lead_id', models.BigIntegerField(blank=True, null=True)),
                ('bitrix_contact_id', models.BigIntegerField(blank=True, null=True)),
                ('bitrix_synced', models.BooleanField(default=False)),
                ('bitrix_user_id', models.IntegerField(blank=True, null=True, verbose_name='Bitrix24 User ID used for this call')),
                ('call_status', models.CharField(choices=[('registered', 'Registered in Bitrix24'), ('completed', 'Completed'), ('failed', 'Failed'), ('recording_uploaded', 'Recording Uploaded')], default='registered', max_length=20, verbose_name='Call synchronization status')),
                ('bitrix_registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitrix24 registration timestamp')),
                ('bitrix_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitrix24 finish timestamp')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error details if sync failed')),
                ('caller_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caller name from contacts')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Call start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Call end time')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Call was answered')),
                ('recording_duration', models.IntegerField(default=0, verbose_name='Actual recording duration in seconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Bitrix24SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('call_register', 'Call Registration'), ('call_finish', 'Call Finish'), ('recording_upload', 'Recording Upload'), ('lead_update', 'Lead Update')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=10)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0, verbose_name='API call duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='calls.calllog')),
            ],
            options={
                'verbose_name': 'Bitrix24 Sync Log',
                'verbose_name_plural': 'Bitrix24 Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['phone_number'], name='calls_calll_phone_n_421b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['timestamp'], name='calls_calll_timesta_ec03bc_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_type'], name='calls_calll_call_ty_df6656_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['user', 'timestamp'], name='calls_calll_user_id_e03eca_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['bitrix_lead_id'], name='calls_calll_bitrix__628993_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['recording_uploaded_to_bitrix'], name='calls_calll_recordi_4808de_idx'),
        ),
        migrations.AddConstraint(
            model_name='calllog',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 0)), name='call_duration_positive'),
        ),
    ]
