# Generated by Django 4.2+ on 2025-01-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix24UserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.IntegerField(verbose_name='Bitrix24 User ID')),
                ('bitrix_user_name', models.CharField(blank=True, max_length=255, verbose_name='Bitrix24 User Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitrix24 User Mapping',
                'verbose_name_plural': 'Bitrix24 User Mappings',
            },
        ),
        migrations.CreateModel(
            name='Bitrix24SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('call_register', 'Call Registration'), ('call_finish', 'Call Finish'), ('recording_upload', 'Recording Upload'), ('lead_update', 'Lead Update')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=10)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0, verbose_name='API call duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='calls.calllog')),
            ],
            options={
                'verbose_name': 'Bitrix24 Sync Log',
                'verbose_name_plural': 'Bitrix24 Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]